DFC.App.DiscoverSkillsCareers.UnitTests/DFC.App.DiscoverSkillsCareers.UnitTests.csproj
DFC.App.DiscoverSkillsCareers.sln
DFC.App.DiscoverSkillsCareers/DFC.App.DiscoverSkillsCareers.csproj
Resources/ArmTemplates/parameters.json
Resources/ArmTemplates/template.json
Resources/ArmTemplates/test-parameters.json
Resources/AzureDevOps/GitVersion.yml
Resources/AzureDevOps/azure-pipelines.yml

Added generic web app ARM template, build and test step in build and fixed GUIDs so sonar will run

NCSD-2674: Arm template

---

DFC.App.DiscoverSkillsCareers/Constants/RouteName.cs
DFC.App.DiscoverSkillsCareers/PageRegistration/registration.json
DFC.App.DiscoverSkillsCareers/Properties/launchSettings.json

Added registration document.

---

Resources/ArmTemplates/parameters.json
Resources/ArmTemplates/template.json
Resources/ArmTemplates/test-parameters.json

Added app settings for apim and Job Profile Overview URLs

NCSD-2813: app settings

---

Resources/ArmTemplates/parameters.json
Resources/ArmTemplates/template.json
Resources/ArmTemplates/test-parameters.json

App settings to get APIM / CDN calls working

NCSD-2966: App settings

---

DFC.App.DiscoverSkillsCareers/appsettings.template.json
Resources/ArmTemplates/parameters.json
Resources/ArmTemplates/template.json
Resources/ArmTemplates/test-parameters.json

Email and SMS template IDs for use with the Gov Notify service

NCSD-2966: Gov Notify Ids

---

Resources/ArmTemplates/template.json

NCSD-2966: app settings fix

---

DFC.App.DiscoverSkillsCareers.Core/Constants/DateTimeFormat.cs
DFC.App.DiscoverSkillsCareers.Models/Common/NotifyOptions.cs
DFC.App.DiscoverSkillsCareers.Services.UnitTests/ServiceTests/ApiServiceTests.cs
DFC.App.DiscoverSkillsCareers.Services/Api/ApiService.cs
DFC.App.DiscoverSkillsCareers.Services/Contracts/IApiService.cs
DFC.App.DiscoverSkillsCareers.UnitTests/Controllers.Assessment/IndexGetTests.cs
DFC.App.DiscoverSkillsCareers.UnitTests/Controllers.Assessment/NewTests.cs
DFC.App.DiscoverSkillsCareers.UnitTests/Controllers.Assessment/ReferenceGetTests.cs
DFC.App.DiscoverSkillsCareers.UnitTests/Controllers.Assessment/ReferencePostTests.cs
DFC.App.DiscoverSkillsCareers/Controllers/AssessmentController.cs
DFC.App.DiscoverSkillsCareers/Startup.cs
DFC.App.DiscoverSkillsCareers/ViewModels/AssessmentEmailPostRequest.cs
DFC.App.DiscoverSkillsCareers/Views/Assessment/EmailSent.cshtml

Added more markup to emailsent view.
Added logging when email fails

Email assessment now working.

---

.editorconfig
DFC.App.DiscoverSkillsCareers.Services.UnitTests/ServiceAPITests/ResultsApiServiceTests.cs
DFC.App.DiscoverSkillsCareers.Services.UnitTests/ServiceTests/AssessmentServiceTests.cs
DFC.App.DiscoverSkillsCareers.Services.UnitTests/ServiceTests/ResultsServiceTests.cs
DFC.App.DiscoverSkillsCareers.Services/Contracts/IAssessmentService.cs
DFC.App.DiscoverSkillsCareers.Services/Services/AssessmentService.cs
DFC.App.DiscoverSkillsCareers.UnitTests/Controllers.Assessment/ReloadTests.cs
DFC.App.DiscoverSkillsCareers/Controllers/AssessmentController.cs
DFC.App.DiscoverSkillsCareers/Controllers/HomeController.cs
DFC.App.DiscoverSkillsCareers/Startup.cs

Added handler for when email is sent.

---

DFC.App.DiscoverSkillsCareers.UnitTests/Controllers.Result/JobProfileOverviewsTests.cs
DFC.App.DiscoverSkillsCareers/Controllers/ResultsController.cs
DFC.App.DiscoverSkillsCareers/Startup.cs
DFC.App.DiscoverSkillsCareers/Views/FilterQuestions/Complete.cshtml

Fixed issue with routing parameter and renamed route.

Fixed issue with category parameter and changed contoller action name

---

DFC.App.DiscoverSkillsCareers.UnitTests/Controllers.FilterQuestions/IndexPostTests.cs
DFC.App.DiscoverSkillsCareers/Controllers/CompositeController.cs
DFC.App.DiscoverSkillsCareers/Controllers/FilterQuestionsController.cs
DFC.App.DiscoverSkillsCareers/Views/FilterQuestions/Index.cshtml
DFC.App.DiscoverSkillsCareers/Views/Results/Index.cshtml
DFC.App.DiscoverSkillsCareers/Views/Results/ResultsByCategory.cshtml
DFC.App.DiscoverSkillsCareers/Views/Results/_JobCategories.cshtml
DFC.App.DiscoverSkillsCareers/Views/Results/_Print.cshtml
DFC.App.DiscoverSkillsCareers/Views/Results/_ResultsHeader.cshtml

Remove hero banner from assesment complete

Remove hero banner from assesment complete

---

DFC.App.DiscoverSkillsCareers/Views/Assessment/Email.cshtml
DFC.App.DiscoverSkillsCareers/Views/Assessment/Index.cshtml

Fix for email button not working with enter key.

---

DFC.App.DiscoverSkillsCareers/Views/Assessment/Email.cshtml
DFC.App.DiscoverSkillsCareers/Views/Assessment/EmailSent.cshtml
DFC.App.DiscoverSkillsCareers/Views/Assessment/Reference.cshtml
DFC.App.DiscoverSkillsCareers/Views/Assessment/ReferenceSent.cshtml
DFC.App.DiscoverSkillsCareers/Views/Assessment/Save.cshtml

Tweeks to styles

---

DFC.App.DiscoverSkillsCareers/Controllers/AssessmentController.cs
DFC.App.DiscoverSkillsCareers/Views/Assessment/Email.cshtml
DFC.App.DiscoverSkillsCareers/Views/Assessment/EmailSent.cshtml

Changes for size of email screens

Style changes for email pages

---

DFC.App.DiscoverSkillsCareers/Views/Assessment/Email.cshtml

Moved send button and uncommented error summary

---

DFC.App.DiscoverSkillsCareers/Controllers/AssessmentController.cs
DFC.App.DiscoverSkillsCareers/Views/Assessment/EmailSent.cshtml

Added temp data for email sent.

Added temp data for email sent

---

DFC.App.DiscoverSkillsCareers/Views/Results/_JobCategories.cshtml

Force route to work out filter assessment progress

Force route to work out filter assessesment progress

---

Resources/ArmTemplates/template.json

As per NCSD-3304 added following app-settings
ExternalLinkOptions__MatchSkillsResultsEndpoint

NCSD-3304-AppSettings-Dysac-Comp-UI

---

DFC.App.DiscoverSkillsCareers.Services.UnitTests/NotificationServiceTests/NotificationServiceTests.cs
DFC.App.DiscoverSkillsCareers.Services.UnitTests/ServiceTests/AssessmentServiceTests.cs
DFC.App.DiscoverSkillsCareers.Services/Contracts/INotificationService.cs
DFC.App.DiscoverSkillsCareers.Services/DFC.App.DiscoverSkillsCareers.Services.csproj
DFC.App.DiscoverSkillsCareers.Services/NuGet.config
DFC.App.DiscoverSkillsCareers.Services/Services/AssessmentService.cs
DFC.App.DiscoverSkillsCareers.Services/Services/NotificationService.cs
DFC.App.DiscoverSkillsCareers.Services/Services/WebhooksService.cs
DFC.App.DiscoverSkillsCareers/NuGet.config
DFC.App.DiscoverSkillsCareers/Startup.cs
Resources/ArmTemplates/template.json

- Add Tests for notification service
- Add Package reference for Notify

- Add E-mail / SMS Support

---

DFC.App.DiscoverSkillsCareers.Services.UnitTests/DFC.App.DiscoverSkillsCareers.Services.UnitTests.csproj
DFC.App.DiscoverSkillsCareers.Services.UnitTests/NuGet.config
DFC.App.DiscoverSkillsCareers/NuGet.config
DFC.App.DiscoverSkillsCareers/Startup.cs
DFC.App.DiscoverSkillsCareers/appsettings.template.json

- Add NuGet config to other required projects
- Add API Key template for Notify

- Fix Notify issues

---

DFC.App.DiscoverSkillsCareers.Services/Services/ResultsService.cs
DFC.App.DiscoverSkillsCareers/Controllers/ResultsController.cs

Add null checks for category when ID isn't passed in to return statement

- added null checks

---

DFC.App.DiscoverSkillsCareers.Services.UnitTests/AssessmentCalculationServiceTests/AssessmentCalculationServiceTests.cs
DFC.App.DiscoverSkillsCareers.Services/Services/AssessmentCalculationService.cs

- Small fix for unintended bug

Hotfix logging trait fix

---

DFC.App.DiscoverSkillsCareers.Services.UnitTests/ServiceTests/CacheReloadServiceTests.cs
DFC.App.DiscoverSkillsCareers.Services/Services/CacheReloadService.cs
DFC.App.DiscoverSkillsCareers.Services/Services/WebhooksService.cs
DFC.App.DiscoverSkillsCareers.UnitTests/Controllers.Sitemap/SitemapTests.cs
DFC.App.DiscoverSkillsCareers/Controllers/SitemapController.cs
DFC.App.DiscoverSkillsCareers/Controllers/WebhooksController.cs
DFC.App.DiscoverSkillsCareers/Extensions/HttpRequestExtensions.cs
DFC.App.DiscoverSkillsCareers/Models/Sitemap.cs
DFC.App.DiscoverSkillsCareers/Models/SitemapImage.cs
DFC.App.DiscoverSkillsCareers/Models/SitemapLocation.cs
PageRegistration/registration.json

- Stop pulling in the Skill type as its own standalone item
- Handle new items in webhook
- Add sitemap section

Skill changes, webhook changes + sitemap

---

DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/DFC.App.DiscoverSkillsCareers.UI.FunctionalTests.csproj

changed appsettings.template.json to appsettings-template.json

appsettings-change

---

DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/DFC.App.DiscoverSkillsCareers.UI.FunctionalTests.csproj
DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/Features/DYSAC.feature
DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/Features/DYSAC.feature.cs
DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/Helpers/Traits.cs
DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/PageObjects/YourResultsPage.cs
DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/Result/dashboard.html
DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/Result/index.html
DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/StepDefinitions/DYSACSteps.cs

Chrome driver downgraded to 94.0.4606.4101

---

DFC.App.DiscoverSkillsCareers.Core/DFC.App.DiscoverSkillsCareers.Core.csproj
DFC.App.DiscoverSkillsCareers.Migration/DFC.App.DiscoverSkillsCareers.Migration.csproj
DFC.App.DiscoverSkillsCareers.Models/DFC.App.DiscoverSkillsCareers.Models.csproj
DFC.App.DiscoverSkillsCareers.Services.UnitTests/DFC.App.DiscoverSkillsCareers.Services.UnitTests.csproj
DFC.App.DiscoverSkillsCareers.Services/DFC.App.DiscoverSkillsCareers.Services.csproj
DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/DFC.App.DiscoverSkillsCareers.UI.FunctionalTests.csproj
DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/EnvironmentSettings.cs
DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/Extensions/WebDriverExtension.cs
DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/Features/DYSAC.feature
DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/Features/DYSAC.feature.cs
DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/PageObjects/DysacPage.cs
DFC.App.DiscoverSkillsCareers.UI.FunctionalTests/PageObjects/YourResultsPage.cs
DFC.App.DiscoverSkillsCareers.UnitTests/DFC.App.DiscoverSkillsCareers.UnitTests.csproj
DFC.App.DiscoverSkillsCareers/Controllers/CompositeController.cs
DFC.App.DiscoverSkillsCareers/DFC.App.DiscoverSkillsCareers.csproj
Resources/ArmTemplates/template.json
Resources/AzureDevOps/azure-pipelines.yml

* NCSLT-1565 changing the setting for running the fuctionaltests.
* NCSLT-1565 Changing TC23,TC24 JobProfiles
* dotnet 6 upgrade
* remove dotnecore reference from azure-pipeline.yml
* DFC.Content.Pkg.Netcore dotnet6 upgrade
* Updated Rollforward options
* Updated Chrome version
* Fixed 404 not found on head endpoint for assessment/new
---------

Merge Release 27.1 to master now live 

---

DFC.App.DiscoverSkillsCareers.UnitTests/Controllers.Assessment/NewTests.cs
DFC.App.DiscoverSkillsCareers/Controllers/AssessmentController.cs

* Removed HttpGet from AssessmentController
* Revert "Removed HttpGet from AssessmentController"
This reverts commit 11ad07854d8b49d111723691ee69959a56d4b9d8.
* Changed to NoContent
* Updated tests to show new response code
---------

Merge Release 37 to master

---

DFC.App.DiscoverSkillsCareers/Views/Composite/HeroBanner.cshtml
DFC.App.DiscoverSkillsCareers/Views/Results/_ResultsHeader.cshtml

https://sfa-gov-uk.visualstudio.com/National%20Careers%20Service%20(NCS)/_workitems/edit/144498

144498: Implement environment-specific URLs for DYSAC  header images 

---

Resources/ArmTemplates/parameters.json
Resources/ArmTemplates/template.json
Resources/ArmTemplates/test-parameters.json

Modified ARM template to reference a log analytics workspace.

Migrate workspace app insights

---

DFC.App.DiscoverSkillsCareers/Views/Results/_ResultsHeader.cshtml

Merging 166621 into release 56 branch

updating images for DYSAC results

---

DFC.App.DiscoverSkillsCareers.Services/DFC.App.DiscoverSkillsCareers.Services.csproj
DFC.App.DiscoverSkillsCareers.Services/Helpers/JobCategoryHelper.cs
DFC.App.DiscoverSkillsCareers.Services/Services/AssessmentCalculationService.cs
DFC.App.DiscoverSkillsCareers.Services/Services/AssessmentService.cs
DFC.App.DiscoverSkillsCareers/Controllers/HomeController.cs
DFC.App.DiscoverSkillsCareers/Controllers/ResultsController.cs
DFC.App.DiscoverSkillsCareers/DFC.App.DiscoverSkillsCareers.csproj
DFC.App.DiscoverSkillsCareers/Startup.cs
DFC.App.DiscoverSkillsCareers/appsettings.template.json
Resources/ArmTemplates/parameters.json
Resources/ArmTemplates/template.json
Resources/ArmTemplates/test-parameters.json

This is related to:
175299- SS: Review Ticket - Implement Cache Expiry for Different Apps

merge Release/live service/68 into master
